### ISSUE TITLE
accessing Np1DArrayFp32 fails pyright type check

### ISSUE THREAD

**Issue by samimia-swks** [caniko/pydantic-numpy#55] opened 2024-11-23 02:48 UTC
I am using python 3.12 and pydantic-numpy v7.0.0 with vscode (pylance). 
This example : 
```
import numpy as np
import pydantic_numpy.typing as pnd
from pydantic import BaseModel

class MyModel(BaseModel):
    k: pnd.Np1DArrayFp32

model = MyModel(k=np.array([1, 2]))

print(model.k[1])  
```
reports 
```
"__getitem__" method not defined on type "FilePath"Pylance[reportIndexIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIndexIssue)
"__getitem__" method not defined on type "MultiArrayNumpyFile"Pylance[reportIndexIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportIndexIssue)
(variable) k: Np1DArrayFp32
```

**Comment by caniko** [comment] 2024-12-17 21:09
@futurwasfree could you take a look at this?

**Comment by futurewasfree** [comment] 2024-12-18 20:00
Hi! 
And yes, I could confirm this.

And that's why I was advocating previously towards having "strict" type notation without Union types:
`Union[np.ndarray[tuple[int], np.dtype[np.float32]], FilePath, MultiArrayNumpyFile]` becomes just `np.ndarray[tuple[int], np.dtype[np.float32]]` ?
so that our models always represent type after validation and coercion.

What do you think, @caniko ?

**Comment by caniko** [comment] 2024-12-21 07:09
@futurwasfree, this makes sense! Thank you for the clarification, let's move forward with your proposal! Mind if I assign this to you?

**Comment by futurewasfree** [comment] 2024-12-21 08:33
Don't mind at all! Will take a look soon-ish..

**Comment by futurewasfree** [comment] 2024-12-21 12:33
Can't create branches directly in this repo, used my fork and this PR: https://github.com/caniko/pydantic-numpy/pull/56 to address it

**Comment by caniko** [comment] 2024-12-22 12:13
Thanks! Will take a look

> Can't create branches directly in this repo

Even I don't do this, proceed as you are; it is the norm.

**Comment by caniko** [comment] 2024-12-22 14:06
@samimia-swks and @futurwasfree for these bases, could you try using the `pydantic_numpy.typing.strict` module instead when requiring pyright typesafety? If not, why?

**Comment by caniko** [comment] 2024-12-23 08:30
Closing because the basis of the issue is false; the base `pydantic_numpy.typing` module is not typesafe! Currently, this is unclear, apologies!

Closing, will make the typesafe submodule default in an upcoming PR!

**Closed as completed by caniko** 2024-12-23 08:30 UTC
Labels: invalid
